name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ops-preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Ops preflight
        run: node scripts/ops-preflight.mjs

  sentry-release:
    if: ${{ secrets.SENTRY_AUTH_TOKEN != '' && (github.event_name == 'push') }}
    runs-on: ubuntu-latest
    needs: ops-preflight
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ vars.SENTRY_ENVIRONMENT || 'production' }}
          version: ${{ github.sha }}
